### ISSUE TITLE
Organize PDF folder into basic, combine, and physics subfolders

### ISSUE THREAD

**Issue by pandeyhs** [GooFit/GooFit#74]

**Comment by henryiii** [comment]
@pandeyhs I'd love to have this in before GooFit 2.0 next week. Please come by if you'd like help getting started.

**Comment by henryiii** [comment]
Here are the main points to watch for:

## ModernizeGooFit
Remember to update `scripts/ModernizeGooFit.py`. Here is an example of a line to add at the end of the list you find there:
```python
     (r'["<]goofit/PDFs/AddPdf.h[">]', '"goofit/PDFs/combine/AddPdf.h"'),
```

Note that I've forgotten to add commas to a few of the lines above it, so it won't run until you add those missing commas.

To run this, do something like `./scripts/ModernizeGooFit.py src/PDFs/*` to convert all includes in the PDF source directory automatically. This is also used to help users convert their code. You will need to have Plumbum installed (`pip install plumbum`).

## CMakeLists.txt 

The file `src/PDFs/CMakeLists.txt` will need to be manually updated, even if you only move the headers (since it also lists those).

## Notes on files

`GooPdf`, `AllPdfs`, and `PdfBase` should stay where they are. "basic" pdfs should never call a "physics" pdf, but the other direction is possible. Basic physics PDFs, like BWPdf, should be "basic"; "physics" is for the interconnected multi-file PDF systems like Tddp4, etc.

**Comment by pandeyhs** [comment]
./scripts/ModernizeGooFit.py src/PDFs/* 
This command only works on the pdfs in the src folder. I currently trying to move the header files first, and for that i am using  ./scripts/ModernizeGooFit.py include/goofit/PDFs/*, it's giving me this error
![image](https://cloud.githubusercontent.com/assets/15573522/26473192/0f55d492-4178-11e7-90a5-0ffbadf66aa0.png)

I am not sure what's going wrong.

**Comment by henryiii** [comment]
That's not the best error message. The command is picking up the folder and trying to convert that (that is, the folder itself, not the contents). Use:
```bash
./scripts/ModernizeGooFit.py file1 file2 file3 ...
```

Please remember to git pull, I brought your source branch up to date with current master this morning.

**Comment by pandeyhs** [comment]
I am getting the same error. For some reason it is trying to find src, and when I looked into the ModernizedGoofFit.py file I found src in there, it could be related to that. 

./scripts/ModernizeGooFit.py src/PDFs/ this command is working just fine.

**Comment by henryiii** [comment]
The `src` [here](https://github.com/GooFit/GooFit/blob/f8d9e63d5bb26a33f1e2c42c7f26d0d926906122/scripts/ModernizeGooFit.py#L164-L165) is just a parameter, it would be better to call it "input_files" or something like that. Try:
```bash
 ./scripts/ModernizeGooFit.py include/goofit/PDFs/*.py
```

and

```bash
 ./scripts/ModernizeGooFit.py include/goofit/PDFs/basic/*.py
```

The [* syntax is the shell](http://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm), not Python, so maybe do this to see what it's actually turning into:
```
echo include/goofit/PDFs/*
echo include/goofit/PDFs/*.py
```

You'll notice that the first line captures the directory you have created also, which the script does not know how to process (since it processes only files).

**Comment by hassec** [comment]
Is there a reason why we didn't introduce this folder structure in the `src` folder as well?

**Comment by henryiii** [comment]
We changed the include folder structure before 2.0 since it changes the API. The user does not change any code if we move the src files around, so it was lower priority. We probably should go ahead and move them. @pandeyhs , the `CMakeLists.txt` in `/src/PDFs` and the locations of the files are the only things that would change. It should be a separate PR.

**Comment by hassec** [comment]
just a gentle reminder that this still needs to be resolved....
Would be nice to get this done soon as it should have made it in the release IMHO
